services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      args:
        API_KEY: ${API_KEY}
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    container_name: restaurant-backend
    ports:
      - "7001:3001"
    environment:
      NODE_ENV: production
      API_KEY: ${API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      DATABASE_URL: "postgresql://postgres:postgres@db:5435/postgres"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: restaurant-frontend
    ports:
      - "7000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
