services:
  backend:
    build:
      context: ./backend
      args:
        API_KEY: ${API_KEY}
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    container_name: restaurant-backend
    ports:
      - "7001:3001"
    volumes:
      - sqlite_data:/app/prisma
    environment:
      NODE_ENV: production
      API_KEY: ${API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: restaurant-frontend
    ports:
      - "7000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
