version: '3.8'
services:
  backend:
    build: ./backend
    container_name: restaurant-backend
    ports:
      - "3001:3001"
    volumes:
      - sqlite_data:/app/prisma
    environment:
      - NODE_ENV=production
      - API_KEY
      - ANTHROPIC_API_KEY
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data: 